### ISSUE TITLE
HandlerSocket won't compile in mariadb 5.2.5

### ISSUE THREAD

**Issue by jsia** [DeNA/HandlerSocket-Plugin-for-MySQL#46]
when i compile handlersocket with mariadb 5.2.5
it produces this error on make

/root/mariadb-5.2.5/sql/handler.h:1577: error: 'virtual int handler::index_read_map(uchar_, const uchar_, key_part_map, ha_rkey_function)' is protected
database.cpp:806: error: within this context
/root/mariadb-5.2.5/sql/handler.h:1577: error: 'virtual int handler::index_read_map(uchar_, const uchar_, key_part_map, ha_rkey_function)' is protected
database.cpp:813: error: within this context
/root/mariadb-5.2.5/sql/handler.h:1593: error: 'virtual int handler::index_prev(uchar_)' is protected
database.cpp:818: error: within this context
/root/mariadb-5.2.5/sql/handler.h:1591: error: 'virtual int handler::index_next(uchar_)' is protected
database.cpp:822: error: within this context
/root/mariadb-5.2.5/sql/handler.h:1599: error: 'virtual int handler::index_next_same(uchar_, const uchar_, uint)' is protected
database.cpp:825: error: within this context
make[2]: **\* [handlersocket_la-database.lo] Error 1
make[2]: Leaving directory `/root/HandlerSocket-Plugin-for-MySQL/handlersocket'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/root/HandlerSocket-Plugin-for-MySQL'
make: **\* [all] Error 2
